/**
 * ==========================================
 * CONFIGURATION
 * Edit this file to add new texts or subtexts
 */
const CONFIG = {
    projectTitle: "Welcome!",
    main_colors: {
        bg_color: "#442D1C",
        text_color: "#84592B"
    },
    subtexts: [
        {
            subtextTitle: "Yellow",
            textContent: `Growing up in my family was a weird experience. Every person in our isolated family has a designated role. My dad is the bread winner and the good cop in parental situations. My mom is the stone cold, serious and bit of a scary leader. My aunt, who lives next door is religious and she values spirituality more than anything. And my older sister is the cool angsty teen everybody wanted to be at some part of their lives (at least I did.) Everybody knew their place and what they wanted to be. Not just family to be exact. In my school, in my neighbourhood, everybody was someone. When it comes to me things get complicated. There is a quote from one of my favorite movies of all time, Mary and Max. Max says “Growing up I wanted to be anybody but myself” and it stuck with me. There were a lot of weird phases in my life. I tried to be like my sister,my couisins that I grew up with, my cool friends at school, random people on internet, those aesthetic girls at pinterest, especially characters in the movies I grew up with. And none of them was the right fit for me. Well in theory it was but something always felt off. I never truly liked any of them, because the feeling of being nobody corrupted my brain. 
So I did what any wise person would do. I literally collected personality traits. First I questioned what would make me unique (mind you I was a kid). And made the resolutions mine, sort of. Biggest example is the color yellow. I always had a obsession with yellow. Everything about it made me feel safe.  When I learned that only %3 of the people in the world’s favorite color was yellow, it clicked to me. I HAD A UNIQUE TRAIT. Don’t get me wrong I am not being performative about yellow. I am pretty sure a lot of people love yellow now. But it was one of the rare moments that made me feel special. I know it sounds stupid for a lot of reasons but anything after this went downhill. 
Highschool in general has a lot of core memories for me. From the second I started ninth grade, i hated everyhing about me. The way I looked, the way I talked, the way I thought, the way I acted... Every single thing about me was wrong. And its shocking to a lot of people in my life because I always had this act going on about knowing who I was and who I wanted to be. But the truth was, I had no idea about who I was, especially about who I wanted to be. That part of my life was very diffucult. And for my family, where everybody knew who they were, I was so out of place. They made me feel like I was ungrateful for being like this. I was lost at home, at school, at my dorm, in any place you can think of. Nobody knowed who I was including me. It was like a movie where every scene was directed by someone else.  
Now I am a senior. The pressure is making me feel so stressed overall. I still have no idea what I am going to do with my life. But maybe that is the exciting part of life. Anything can happen and nobody can predict it. Even though I am still in a blank page, I learned some stuff about myself through out this weird growing up journey that I had.
I love making people laugh, I love glittery stuff, I love talking nonstop. Do they make me who I am or are they just permament traits? That is a mystery again but its okay, it is a part of growing up I guess. And last but not least, I love the color yellow with all my heart.
`,
            authorName: "Zelal Sara Aslan",
            authorAge: 17,
            authorTag: "High School",
            bg_image_url: "resources/backgrounds/yellow.jpg",
            bg_image_blur: "10px",
            bg_color: "#FFEE99",
            text_color: "#000000"
        },
        {
            subtextTitle: "Scissors",
            textContent: `One morning when I woke up, everything could have changed. I could have woken up as a princess, just like in the movies, or I could have opened my eyes in another world. But in my world, whether in a classroom full of my peers or during those forced visits to neighbors; my mind, which turned everything in the world into an adventure and every object into a magical medallion, realized this through the words of those facing me and the words reaching my heart from my ears. To most people, my medallion must have been ugliness.
“Eat a little less, your breasts are too big for your age, isn’t it time to see the dentist, if you eat too much you’ll end up as big as the neighbor’s daughter who has no arm”—and of course, as I grew older, different versions of this would follow. Peer bullying, your mom looking at you and comparing you to her youth photos… Being dragged to a dietitian against my will.
I think I always knew there was something wrong with my appearance; I’d try not to eat for days and, thinking nothing changed, I’d end up stuffing even more into my mouth out of frustration. Opening my eyes to the times I remember, all the way up to my 20s. In the early days of my adolescence, while staying with my grandmother, I’d eat peppers and cucumbers to avoid eating much, then try to make myself vomit; as I got older, on days we’d go to pubs, I’d either binge on what I’d eaten that morning or stop eating altogether, all because we’d be drinking beer. At 14, standing naked in front of a mirror, I’d imagine cutting pieces off my body as if I were slicing dough. 
In the remote corners of the internet, where no one was watching and my family had no idea or didn’t care, there were some pretty appealing ideas about what I could do regarding this. In my mind, I already looked and lived differently. I would find a way to come to terms with my own body. With the onset of quarantine, this had already become a topic pushed to the sidelines. For someone like me who didn’t feel comfortable in my own body—someone who, when asked to describe myself, would say, “I’m a fat, ugly girl”—it had created more friendly adjectives I could add to that description. But I can say that this only led to adding more weight to the bag. 
That’s why, when I emerged from quarantine and stepped into my senior year of high school, I found myself facing a determination I never expected. We young people don’t value the health of our bodies as much as it seems. That’s why we can’t recognize the effects of the weight lost by starving ourselves. Brittle hair and nails, a suddenly weakened immune system, sudden illnesses... 
At the beginning of my college years, I didn’t realize I was wasting away until I ended up in a hospital bed—and even then, I tried to keep going. I remember asking myself at one point, “What’s the point?” Recurring depression, hunger, nausea, and that night in a cold, dark house I’ll never forget. I couldn’t sleep or calm down; I cried as if I were drowning. The city I’d given my life to reach, the ambitions and academic anxieties I’d struggled with, had strung me up on the gallows of my own making. After fruitless suicide attempts and the return of the weight I’d struggled to lose on antidepressants, following diagnoses at a new hospital, I wondered how I would pull myself together, how I could build a home for myself from this rubble. 
I remembered the girl who set goals for herself with bright, curious eyes, who chased animals through the green districts of the Aegean, and who regarded archaeological sites as her second home. I made the soil and stones of my hometown—where I returned after transitioning to a healthy diet—my own nest. Instead of the money I spent shopping for the homeland, or the internet expenses under the pretense of studying at a café, I replaced those online purchases with simply the life I’d seen and liked on Instagram beforehand. When the time comes: studies, healthy food, camps, hikes, and horses.
When I opened my eyes again without a veil, there was no hunger or nausea in my world. I galloped toward the people I would judge, and shared that tiramisu with my friends. I saved up my money and traveled from Istanbul to Samos. The effort I put in wasn’t wasted on nights spent starving in a cold city or on pointless ambitions. Now my hair is growing, my nails aren’t breaking. When I look in the mirror, I don’t see a pair of scissors in my hand; my hand holds either a pen or trash, sometimes grass, sometimes reins, but I’ve sworn never to pick up the scissors again. One morning when I woke up, I woke up feeling like myself, not like something else.
`,
            authorName: "Naz Tekin",
            authorAge: 21,
            authorTag: "Tourist Guiding",
            bg_image_url: "resources/backgrounds/scissors.jpg",
            bg_image_blur: "12px",
            bg_color: "#D7E0B3",
            text_color: "#000000"
        },
        {
            subtextTitle: "Hiraeth",
            textContent: `To move back and forth between two cities and never feeling that you fully belong to either—this is, in truth, an experience far more common among students than one might think. 
From the outside, it can be explained with strong, sensible reasons: “to build a better life,” or “to learn how stand on your own feet.” Or, to be a bit more honest, we believe it can be explained that way. But once you truly live inside this system, the story no longer feels so clear, nor so heroic. Because sometimes, while you think you are making decisions about your own life, you don’t even realize that you are already walking along a path drawn long before you arrived. 
After all, you have been inside a system for years. From tutoring centers to school, from school back to tutoring centers; dragged from one exam to another. Since childhood, you have grown up with the goal of a “good high school,” then a “good university.” There is always a next stage, another test ahead. Always a sense of rushing, always a preparation… “Don’t worry, just get through this exam, everything else will be easy.” And yet, this preparation never seems to end. As you keep looking forward, you almost never pause to notice what you’ve left behind, or how easily you were swept along by the current. 
Leaving the place where you were born… it is not just moving away. It means leaving behind the streets you walked after class with your closest friends, the neighborhood where every corner holds a memory, the theater you went alone for the first time, perhaps those small moments when you first felt “free.” They may seem small, but they are the pieces that shape who you are. And when life has been already taking certain things from you since the beginning, being pulled away from the few things you can still hold onto feels even heavier. 
Because some places are more than just a family house. They carry your habits, your sounds, your smells. They hold the small details that make you who you are. When you leave that city, you don’t just move away physically, you feel as though you have left a part of yourself behind. When you arrive somewhere new, everything starts from the beginning. The people are new, the streets are unfamiliar, the memories are absent. No one knows you through your past. There, you exist only as who you are in the present. 
And this is where that indescribable sense of emptiness begins, slowly taking over your entire being. Because while you try to build something of your own, you find yourself constantly longing for what you have left behind. As you make a new friend, you think of old ones. As you walk down a new street, old paths appear before your eyes. You try to make every place resemble your hometown; even the sight of your hometown’s license plate can fill you with an urge to cry out in excitement. Even when things are good, they feel incomplete, as if nothing is ever quite whole. 
It is at this point that you begin to ask yourself: Is it truly worth being away from the people you love for the sake of a better future? Or do we tell ourselves, “I am passionate about education,” simply to make peace with it? Is this really what we want, or have we just come to believe that this is what must be? 
Because when things become difficult, when something goes wrong, all those “reasonable explanations” suddenly lose their meaning. And in that moment, the first person you think of is still your mother. It is simple, yet a powerful truth most of us try to ignore. No matter how much one grows, some bonds do not change. 
At the same time, other questions linger in the corners of your mind: Does my father still have to work this hard? Why is my mother still so tired after giving up so many years from her life? While I am here trying to build my life, what are they dealing with back there? And most of all—your siblings… You wonder whether they kept crying, just like the first day, begging you not to go. Maybe they don’t cry anymore, but does that mean they’ve grown used to it, or simply buried it inside? Are they angry with you, do they miss you, or have they made space for your absence in their life? You never quite know. And this uncertainty is one of the most exhausting things a person can carry. This is not just “being an older sister.” It is a bond so deep that it cannot truly be measured. And now, you have left part of that bond to distance. This cannot be explained in kilometers alone. It feels as though you have left behind a piece you once helped grow—as though you are not where you are meant to be. As though something is missing, though you cannot fully name it. 
You wonder: Am I becoming a financial burden to my family? Thinking of all they have done for you, you diminish even your own exhaustion. As if you have no right to feel tired. As if you must keep going, no matter what. And in the middle of all this, without even realizing it, you begin to miss things. Your sibling grows up—but you are not there. You learn about small changes at home from afar. Holidays, birthdays, ordinary dinners… they all become memories, but you are absent from most of them. 
Over time, even your home changes. Small things shift while you are gone. The order changes, people change. When you return, everything feels both familiar and strange. “Is this table new, mom?” “When did you change the carpets?”—and a thousand little details like these. That house is still “your home,” but you no longer feel entirely like a part of it. And this leaves behind a strange question: Am I coming from home, or returning to it? 
And when you stay in a dorm, it is not much different. That too is temporary. Your belongings are limited, your memories are new and often shallow. People come and go. In truth, you are not fully in either place. You belong neither completely here nor there. Over time, this in-between situation stops being a situation and becomes an identity—one that breathes alongside you. 
At some point, you grow tired. You want to say, “I can’t do this.” But even saying that is not easy. Because giving up does not only mean leaving where you are—it means leaving your dreams behind, your efforts, and the expectations placed upon you. And more often than not, people continue not because they cannot give up their dreams, but because they cannot give up those expectations. 
When high school students visit the campus and we complain ironically, “Stop coming, we feel like animals in a zoo,” what is it that we truly miss? Their curious eyes, the way they look at every corner and wonder, “Could I belong here too?” The lightness of not yet having made the biggest decision of their lives? That time when possibilities seemed endless? Or do we miss that pure belief we once carried while preparing for exams—the unshakable faith that everything would fall into place, that if we made the right choice, we would be happy? Perhaps back then, life seemed clearer, more linear. As if one exam would be passed, one choice would be made, and everything else would simply follow. And yet now, standing in the very life we once dreamed of, we know that nothing is quite so certain, nor so simple. 
Perhaps this is why their presence unsettles us. Because they remind us of our former selves—untired, unshaped by disappointment. Perhaps what truly disturbs us is what they see when they look at us: the person they hope to become. And we know, all too well, what that person eventually becomes. 
Education does give you something, yes. Knowledge, new perspectives, new people. But in doing so, it also takes something from you. Perhaps most of all, that sense of belonging. And this loss is not loud—it happens quietly, gradually. You think you are getting used to it. But at some point, you begin to ask yourself harder questions. 
Do the certificates filling your CV truly fill the emptiness inside you? Do your grades, the trainings, the conferences, every line you write—do they really complete you? Or do they merely make your incompleteness look more organized? All those pages of exam questions you solved… marking the right answers, eliminating the wrong ones, will these really help you express yourself? Or have they simply trained you to find the correct answer, leaving you unable to form your own? Because the system always teaches you a “correct” answer. But life, more often than not, asks you to create meaning. 
Be careful, at this very point, after years of trying to find the right answer, you may have postponed expressing yourself. Perhaps this is why, even when you arrive somewhere, there is still an emptiness you cannot name. Because what you carry with you is not who you are, but what you have achieved. And yet, a person is completed not by achievements, but by the connections they build, what they can express, and what they can feel. 
Maybe the real issue is not adapting. Maybe the real question is this: Is this truly the right path, or are you walking it simply because there seems to be no alternative? Because in the end, what remains is not just diplomas, exams, or achievements. Even with all of these, a person can still feel empty. And that emptiness often reduces itself to a single question: Where am I? Perhaps the hardest part of this journey is not failing to arrive somewhere but never quite arriving anywhere at all. 
You carry two people within you, yet you have long forgotten which one is truly you. Are you the person from that city, or the one from the other? Perhaps you are both—but you do not fully belong to either. It is nothing like the answers you memorized for exams, is it? 
You even miss the things you once complained about your mother. What once angered you now feels familiar and distant at the same time. The small arguments with your sibling… moments when you thought, “I wish we’d never speak again.” Now they warm you from within. Your father returning home with bags in his hands, the sound of the door opening, that tired yet familiar presence… all of them are now like small scenes you can no longer reach. 
You feel as though you are caught between the cold bed of your dorm room and your mother’s Sunday breakfast. One is real but incomplete; the other is distant but whole. And perhaps this is exactly where a person gets stuck in between the two. You miss that one word only your father was ever allowed to call you. A word that would mean nothing from anyone else, but from him, it made you you. Because some words belong only to one person, they never sound the same from another. 
You miss having coffee with your closest friend. That ease of talking for hours and feeling like you talked about nothing at all. Even running into friends you had fallen out with, in the most unexpected places… even those awkward, unfinished greetings. Because it is not only the people you miss, but the version of yourself you were with them. 
Were you more comfortable there, or was everything simply more familiar? Are you truly building a new self here, or just trying not to lose the old one? Perhaps the hardest truth is this: sometimes you don’t want to return to your past, you just want to return to the version of yourself in it. And now, you are right in the middle of it. Neither fully gone, nor fully stayed. Ask yourself: Where do you belong? 
Sorry for disturbing you, but you do have an important exam ahead of you. Just a reminder. After all, all of this is your problem, the system doesn’t really care about it.
`,
            authorName: "Sıla Ergin",
            authorAge: 21,
            authorTag: "American Culture and Literature",
            bg_image_url: "resources/backgrounds/hiraeth.jpg",
            bg_color: "#98A9BD",
            text_color: "#FFFFFF"
        },
        {
            subtextTitle: "Dark Opera",
            textContent: `The composers of my concerto are lost; who has stolen the heteronyms within me? We had said that growing up would multiply them, yet with each passing day I gnaw away at all the hopes and aspirations I’ve lost. Sometimes I want to create a revolution in my heart; let the piece’s dominant language be the piano, not the violin. If the preface of my frozen blood flows through the doors I open, then perhaps we can await the seasons, just like Vivaldi.
Moving forward is hard; sometimes even the war inside me pushes me backward. Fighting on the fronts God has opened is very hard; my thoughts can only confront one thing at a time. I love placing the verb at the end of the sentence; it feels like it completes my orchestra. Shields may slip from my hands in battle, and sometimes, in pursuit of my goal, secondary factors are forgotten. Maybe I’m not as smart as I used to be; my narcissistic personality no longer even sees itself as a person. I burned myself the most in those fiery flames; it’s so hard to remember the old me. The detective showed me the evidence in my case; neither the killer nor the victim can be found.
I struggle even to write a simple sentence; believe me, the rhyme at the end isn’t intentional. The music in my ear won’t stop; even if you ring my left ear, you still can’t escape the revolution raging inside me. My soul is drunk; alcohol’s only effect is letting the world digest the tears in my body. I think there’s no antidote for this illness; you must leave me somewhere between Scylla and Charybdis. My illness awaits my 27th year; I’ve sworn to exhale my tainted breath one last time.
My captive soul will never break its chains; I have no teeth left to shatter them. My strength refuses to surrender its will to me; I lack the courage to bear it. The arrows of my feelings were launched into the air, soared to the heavens, and fell to the earth. My ascents in life have faded like a fire; no one poured water on them, yet they left a trail behind, and the sickle was never cast into the field again. Do not plant any sapling or seed in my farm; there is no gardener to tend this garden. Do not trust the old daffodils you sniffed in December; as you see, every flower is far from blooming.
Santa Claus has come with his lights; how happy I am, isn’t it? I should be sparkling! I can’t open my eyes to look around; as if the sun has fallen asleep on purpose, leaving only me behind. I’m unaware of what’s happening; the country is falling apart, yet I’m fixated on magazine covers! People have spilled into the streets; I must realize the cause isn’t kindness, but fanaticism. My own ideals are an idol to me; I must be a barrier against those who shatter them. In the end, everyone loses; as long as I’m the only one who wins! (!)
They’re cutting down the trees of my entire forest; I don’t want the wood you take from my greenery. I stood up without flinching; the cowards watch the cursers from the window. No one knows the truth; the tinted windows seem like the highest curtain. I must worship the king; oh, may his crown not fall from the highest sanctuary! I must die in my own pit; let them lay my shroud as if it were nothing. I must watch the next episode of my series there; the harmony between me and an ordinary citizen continues.
What must I do to move forward? The steps I take can’t take me any further. I say humanity must shatter; the sharpest thorn of my smile no longer hurts. I endure people; perhaps I’ve become the scarecrow in their gardens. They never change; the machine they’ve placed has produced their chips exactly as programmed. Money, love, fame; is this the deepest part of the ocean in all your dreams? Am I living in vain; I can’t reveal the shadow of my iceberg to anyone.
There are some writers who fit you into their novels; their silhouettes are usually the physical form of who I am. In the steps I take, I feel their sentences; I always imagine myself as someone else. I am the only one who knows myself in this world; the portrait I see in the mirror is not me. Dorian Gray lives within me; an aged painting. That is why the skin of those who touch me trembles; a trace of my brush remains on them. The fifth act of my opera is coming; please do not lose your focus.
The colors of my orchestra are gray; I strike my instruments with my harshest tone, living in a dream. The killer within me sees only the deaths of those he loves; he ignites the fires of hell with the tears in his eyes. The sound of the notes rises; I find myself lost in every moment at the ball. It’s as if I’m the only one who doesn’t see the masks; everyone has hidden their ugly faces beneath them. Everyone keeps time with my rhythm; I notice their ingratitude in their dances. They are whatever the music is; I thought I was different, but I wasn’t. Violin, piano, cello, harp—all lies; bring me the next nightmare now.
`,
            authorName: "Halil Emre Sayar",
            authorAge: 22,
            authorTag: "Electrical and Electronics Engineering",
            bg_image_url: "resources/backgrounds/dark_opera.jpg",
            bg_color: "#380B2F",
            text_color: "#FFFFFF"
        },
        {
            subtextTitle: "Turn and Look at the World",
            textContent: `Even before I had put on that robe, I knew that—somewhere deep inside— something wasn’t right. When they asked, “What are you up to?” I would take refuge behind the fortress of “I’m a student,” but there were cracks in those walls. The view outside was unsettling. Still, back then I had a perfect escape: “I don’t think about it now,” I would tell myself. “Let the midterms pass, let me get that diploma—then I’ll deal with the rest.” School was like a mist that both shielded me from the outside world and kept me from facing it. Remaining within that fog felt safer than joining the line of the unemployed waiting beyond it.
And then, in a single day, the mist dissolved. The caps were thrown into the air, congratulations were exchanged, and that word I had trusted so much—“then”—stepped forward and stood right in front of me. There was no midterm week left to hide behind, no “let me just finish this assignment” to cling to. When I took off the robe and set it aside, I realized that the title of “student” had slipped away from me as well—and I didn’t even know what remained in its place.
Now, I am in that infamous “in-between.” Every morning I open my computer to forms, exam dates, well-meaning wishes of “I wish it all turn out well”… Outside, the world keeps spinning, everyone seems to be rushing somewhere. And I stand at the very center of uncertainty. As I try to fit myself into the system out there, I feel myself slowly losing the person within. The “me” outside has to succeed, has to become something respectable. But at night, when my head touches the pillow, that same question lingers:
Is this person I’ve become truly me—or just a stranger shaped by the noise of the outside world?
Looking back, I now understand that the fog didn’t only hide me—it also kept me from seeing the world. Inside it, there were only my own struggles and the muffled voices of others. When the curtain finally lifted, I began to see the world in its bare reality. It wasn’t as terrifying as the exaggerated darkness of social media, but neither was it the rosy tale I had been told.
I feel myself coming to peace. In my ears, a familiar melody echoes: “Dön bak dünyaya” (Turn and look at the world) (Pinhani). This new landscape no longer frightens me. On the contrary, stripped of all the labels that once defined me, I begin to ask: Is my life only just beginning? Perhaps now it is time to set out in search for “me” that has ben silently waiting, somewhere deep inside.
`,
            authorName: "İlhan Bozacıoğlu",
            authorAge: 23,
            authorTag: "Molecular Biology and Genetics",
            bg_image_url: "resources/backgrounds/turn_around_and_look_at_the_world.jpg",
            bg_color: "#C6C9CD",
            text_color: "#000000"
        },
        {
            subtextTitle: "Collective Loneliness",
            textContent: `It’s midnight. In the silence of the room, I hear not just the ticking of the clock, but as if something outside is slowly crumbling, falling to pieces. They call it social decay; but what I feel is more of a void. Everything is slowly being hollowed out from within. Friendships have turned into alliances of self-interest, and greetings into mere attempts to prove we’re still here. It’s as if, with each passing day, the ground we stand on grows a little muddier. Whatever we used to call wrong has now become a rule for survival. It’s as if no one owes anyone anything anymore, and no one has the luxury of loving another simply because they’re human. Everyone is trying to clear their own path by pushing someone else aside. 
The only thing this system promises us is an endless waiting room. In that room, no one is anyone else’s companion. Everyone is preoccupied with stepping on others’ shoulders to climb a little higher, to catch a little more breath. On one hand, we’re forced to keep up with everything, to look good everywhere; on the other, we know we’re not actually getting anywhere. The worst part is this: being fully aware of everything—every absurdity—yet being unable to change a single thing. A person turns into a spectator watching their own life from the outside.  
The greatest thing this system demands of us is that we accept this sense of alienation and loneliness as some kind of failure. They want us to doubt ourselves. Yet this unease may well be our strongest instinct within a broken system. The real problem is finding peace within a decaying structure. Yet if we still feel the pain, that is the only proof that we are still alive, that we have not become part of this rubble. 
That is why knowing that someone else is thinking the exact same things right now is not a blessing, but a necessity. Trying to reach out to someone in this chaos is not a romantic fantasy; it is the only way out of this decay. Because I know that, while everyone lives their own lie, bearing witness to another’s genuine pain is the only honest act we can perform against the system. This isn’t about salvation; it’s simply the way to avoid getting lost in this rubble. Perhaps the real issue isn’t finding an escape route, but realizing that this chaos we’re in isn’t unique to us. That’s all.
`,
            authorName: "Utku Berk Yılmaz",
            authorAge: 21,
            authorTag: "Sociology",
            bg_image_url: "resources/backgrounds/collective_loneliness.jpg",
            bg_image_blur: "13px",
            bg_color: "#DEB3A6",
            text_color: "#000000"
        }
    ]
};
