const hiraeth_text = `To move back and forth between two cities and never feeling that you fully belong to either—this is, in truth, an experience far more common among students than one might think. 
From the outside, it can be explained with strong, sensible reasons: “to build a better life,” or “to learn how to stand on your own feet.” Or, to be a bit more honest, we believe it can be explained that way. But once you truly live inside this system, the story no longer feels so clear, nor so heroic. Because sometimes, while you think you are making decisions about your own life, you don’t even realize that you are already walking along a path drawn long before you arrived. 
After all, you have been inside a system for years. From tutoring centers to school, from school back to tutoring centers; dragged from one exam to another. Since childhood, you have grown up with the goal of a “good high school,” then a “good university.” There is always a next stage, another test ahead. Always a sense of rushing, always a preparation… “Don’t worry, just get through this exam, everything else will be easy.” And yet, this preparation never seems to end. As you keep looking forward, you almost never pause to notice what you’ve left behind, or how easily you were swept along by the current. 
Leaving the place where you were born… it is not just moving away. It means leaving behind the streets you walked after class with your closest friends, the neighborhood where every corner holds a memory, the theater you went alone for the first time, perhaps those small moments when you first felt “free.” They may seem small, but they are the pieces that shape who you are. And when life has been already taking certain things from you since the beginning, being pulled away from the few things you can still hold onto feels even heavier. 
Because some places are more than just a family house. They carry your habits, your sounds, your smells. They hold the small details that make you who you are. When you leave that city, you don’t just move away physically, you feel as though you have left a part of yourself behind. When you arrive somewhere new, everything starts from the beginning. The people are new, the streets are unfamiliar, the memories are absent. No one knows you through your past. There, you exist only as who you are in the present. 
And this is where that indescribable sense of emptiness begins, slowly taking over your entire being. Because while you try to build something of your own, you find yourself constantly longing for what you have left behind. As you make a new friend, you think of old ones. As you walk down a new street, old paths appear before your eyes. You try to make every place resemble your hometown; even the sight of your hometown’s license plate can fill you with an urge to cry out in excitement. Even when things are good, they feel incomplete, as if nothing is ever quite whole. 
It is at this point that you begin to ask yourself: Is it truly worth being away from the people you love for the sake of a better future? Or do we tell ourselves, “I am passionate about education,” simply to make peace with it? Is this really what we want, or have we just come to believe that this is what must be? 
Because when things become difficult, when something goes wrong, all those “reasonable explanations” suddenly lose their meaning. And in that moment, the first person you think of is still your mother. It is simple, yet a powerful truth most of us try to ignore. No matter how much one grows, some bonds do not change. 
At the same time, other questions linger in the corners of your mind: Does my father still have to work this hard? Why is my mother still so tired after giving up so many years from her life? While I am here trying to build my life, what are they dealing with back there? And most of all—your siblings… You wonder whether they kept crying, just like the first day, begging you not to go. Maybe they don’t cry anymore, but does that mean they’ve grown used to it, or simply buried it inside? Are they angry with you, do they miss you, or have they made space for your absence in their life? You never quite know. And this uncertainty is one of the most exhausting things a person can carry. This is not just “being an older sister.” It is a bond so deep that it cannot truly be measured. And now, you have left part of that bond to distance. This cannot be explained in kilometers alone. It feels as though you have left behind a piece you once helped grow—as though you are not where you are meant to be. As though something is missing, though you cannot fully name it. 
You wonder: Am I becoming a financial burden to my family? Thinking of all they have done for you, you diminish even your own exhaustion. As if you have no right to feel tired. As if you must keep going, no matter what. And in the middle of all this, without even realizing it, you begin to miss things. Your sibling grows up—but you are not there. You learn about small changes at home from afar. Holidays, birthdays, ordinary dinners… they all become memories, but you are absent from most of them. 
Over time, even your home changes. Small things shift while you are gone. The order changes, people change. When you return, everything feels both familiar and strange. “Is this table new, mom?” “When did you change the carpets?”—and a thousand little details like these. That house is still “your home,” but you no longer feel entirely like a part of it. And this leaves behind a strange question: Am I coming from home, or returning to it? 
And when you stay in a dorm, it is not much different. That too is temporary. Your belongings are limited, your memories are new and often shallow. People come and go. In truth, you are not fully in either place. You belong neither completely here nor there. Over time, this in-between situation stops being a situation and becomes an identity—one that breathes alongside you. 
At some point, you grow tired. You want to say, “I can’t do this.” But even saying that is not easy. Because giving up does not only mean leaving where you are—it means leaving your dreams behind, your efforts, and the expectations placed upon you. And more often than not, people continue not because they cannot give up their dreams, but because they cannot give up those expectations. 
When high school students visit the campus and we complain ironically, “Stop coming, we feel like animals in a zoo,” what is it that we truly miss? Their curious eyes, the way they look at every corner and wonder, “Could I belong here too?” The lightness of not yet having made the biggest decision of their lives? That time when possibilities seemed endless? Or do we miss that pure belief we once carried while preparing for exams—the unshakable faith that everything would fall into place, that if we made the right choice, we would be happy? Perhaps back then, life seemed clearer, more linear. As if one exam would be passed, one choice would be made, and everything else would simply follow. And yet now, standing in the very life we once dreamed of, we know that nothing is quite so certain, nor so simple. 
Perhaps this is why their presence unsettles us. Because they remind us of our former selves—untired, unshaped by disappointment. Perhaps what truly disturbs us is what they see when they look at us: the person they hope to become. And we know, all too well, what that person eventually becomes. 
Education does give you something, yes. Knowledge, new perspectives, new people. But in doing so, it also takes something from you. Perhaps most of all, that sense of belonging. And this loss is not loud—it happens quietly, gradually. You think you are getting used to it. But at some point, you begin to ask yourself harder questions. 
Do the certificates filling your CV truly fill the emptiness inside you? Do your grades, the trainings, the conferences, every line you write—do they really complete you? Or do they merely make your incompleteness look more organized? All those pages of exam questions you solved… marking the right answers, eliminating the wrong ones, will these really help you express yourself? Or have they simply trained you to find the correct answer, leaving you unable to form your own? Because the system always teaches you a “correct” answer. But life, more often than not, asks you to create meaning. 
Be careful, at this very point, after years of trying to find the right answer, you may have postponed expressing yourself. Perhaps this is why, even when you arrive somewhere, there is still an emptiness you cannot name. Because what you carry with you is not who you are, but what you have achieved. And yet, a person is completed not by achievements, but by the connections they build, what they can express, and what they can feel. 
Maybe the real issue is not adapting. Maybe the real question is this: Is this truly the right path, or are you walking it simply because there seems to be no alternative? Because in the end, what remains is not just diplomas, exams, or achievements. Even with all of these, a person can still feel empty. And that emptiness often reduces itself to a single question: Where am I? Perhaps the hardest part of this journey is not failing to arrive somewhere but never quite arriving anywhere at all. 
You carry two people within you, yet you have long forgotten which one is truly you. Are you the person from that city, or the one from the other? Perhaps you are both—but you do not fully belong to either. It is nothing like the answers you memorized for exams, is it? 
You even miss the things you once complained about your mother. What once angered you now feels familiar and distant at the same time. The small arguments with your sibling… moments when you thought, “I wish we’d never speak again.” Now they warm you from within. Your father returning home with bags in his hands, the sound of the door opening, that tired yet familiar presence… all of them are now like small scenes you can no longer reach. 
You feel as though you are caught between the cold bed of your dorm room and your mother’s Sunday breakfast. One is real but incomplete; the other is distant but whole. And perhaps this is exactly where a person gets stuck in between the two. You miss that one word only your father was ever allowed to call you. A word that would mean nothing from anyone else, but from him, it made you you. Because some words belong only to one person, they never sound the same from another. 
You miss having coffee with your closest friend. That ease of talking for hours and feeling like you talked about nothing at all. Even running into friends you had fallen out with, in the most unexpected places… even those awkward, unfinished greetings. Because it is not only the people you miss, but the version of yourself you were with them. 
Were you more comfortable there, or was everything simply more familiar? Are you truly building a new self here, or just trying not to lose the old one? Perhaps the hardest truth is this: sometimes you don’t want to return to your past, you just want to return to the version of yourself in it. And now, you are right in the middle of it. Neither fully gone, nor fully stayed. Ask yourself: Where do you belong? 
Sorry for disturbing you, but you do have an important exam ahead of you. Just a reminder. After all, all of this is your problem, the system doesn’t really care about it.
`;
