const scissors_text = `One morning when I woke up, everything could have changed. I could have woken up as a princess, just like in the movies, or I could have opened my eyes in another world. But in my world, whether in a classroom full of my peers or during those forced visits to neighbors; my mind, which turned everything in the world into an adventure and every object into a magical medallion, realized this through the words of those facing me and the words reaching my heart from my ears. To most people, my medallion must have been ugliness.
“Eat a little less, your breasts are too big for your age, isn’t it time to see the dentist, if you eat too much you’ll end up as big as the neighbor’s daughter who has no arm”—and of course, as I grew older, different versions of this would follow. Peer bullying, your mom looking at you and comparing you to her youth photos… Being dragged to a dietitian against my will.
I think I always knew there was something wrong with my appearance; I’d try not to eat for days and, thinking nothing changed, I’d end up stuffing even more into my mouth out of frustration. Opening my eyes to the times I remember, all the way up to my 20s. In the early days of my adolescence, while staying with my grandmother, I’d eat peppers and cucumbers to avoid eating much, then try to make myself vomit; as I got older, on days we’d go to pubs, I’d either binge on what I’d eaten that morning or stop eating altogether, all because we’d be drinking beer. At 14, standing naked in front of a mirror, I’d imagine cutting pieces off my body as if I were slicing dough. 
In the remote corners of the internet, where no one was watching and my family had no idea or didn’t care, there were some pretty appealing ideas about what I could do regarding this. In my mind, I already looked and lived differently. I would find a way to come to terms with my own body. With the onset of quarantine, this had already become a topic pushed to the sidelines. For someone like me who didn’t feel comfortable in my own body—someone who, when asked to describe myself, would say, “I’m a fat, ugly girl”—it had created more friendly adjectives I could add to that description. But I can say that this only led to adding more weight to the bag. 
That’s why, when I emerged from quarantine and stepped into my senior year of high school, I found myself facing a determination I never expected. We young people don’t value the health of our bodies as much as it seems. That’s why we can’t recognize the effects of the weight lost by starving ourselves. Brittle hair and nails, a suddenly weakened immune system, sudden illnesses... 
At the beginning of my college years, I didn’t realize I was wasting away until I ended up in a hospital bed—and even then, I tried to keep going. I remember asking myself at one point, “What’s the point?” Recurring depression, hunger, nausea, and that night in a cold, dark house I’ll never forget. I couldn’t sleep or calm down; I cried as if I were drowning. The city I’d given my life to reach, the ambitions and academic anxieties I’d struggled with, had strung me up on the gallows of my own making. After fruitless suicide attempts and the return of the weight I’d struggled to lose on antidepressants, following diagnoses at a new hospital, I wondered how I would pull myself together, how I could build a home for myself from this rubble. 
I remembered the girl who set goals for herself with bright, curious eyes, who chased animals through the green districts of the Aegean, and who regarded archaeological sites as her second home. I made the soil and stones of my hometown—where I returned after transitioning to a healthy diet—my own nest. Instead of the money I spent shopping for the homeland, or the internet expenses under the pretense of studying at a café, I replaced those online purchases with simply the life I’d seen and liked on Instagram beforehand. When the time comes: studies, healthy food, camps, hikes, and horses.
When I opened my eyes again without a veil, there was no hunger or nausea in my world. I galloped toward the people I would judge, and shared that tiramisu with my friends. I saved up my money and traveled from Istanbul to Samos. The effort I put in wasn’t wasted on nights spent starving in a cold city or on pointless ambitions. Now my hair is growing, my nails aren’t breaking. When I look in the mirror, I don’t see a pair of scissors in my hand; my hand holds either a pen or trash, sometimes grass, sometimes reins, but I’ve sworn never to pick up the scissors again. One morning when I woke up, I woke up feeling like myself, not like something else.
`
